main: me.zeronull.spawnarena.SpawnArena
name: SpawnArena
version: 1.0.0
api-version: '1.20'
softdepend:
  - WorldGuard
  - BetterTeams
folia-supported: true

commands:
  joinarenaqueue:
    description: join queue
    permission: spawnarena.joinarenaqueue
    permission-message: "§cYou don't have permission!"
  setarenaspawn:
    description: join queue
    permission: spawnarena.setarenaspawn
    permission-message: "§cYou don't have permission!"
  createarena:
    description: Create an arena
    permission: spawnarena.createarena
    permission-message: "§cYou don't have permission!"
  togglearenamode:
    description: Alter the arena mode
    permission: spawnarena.togglearenamode
    permission-message: "§cYou don't have permission!"
  setupfight:
    description: Add 2 players to the queue to ensure they fight each other
    permission: spawnarena.setupfight
    permission-message: "§cYou don't have permission!"
  setarenaschematic:
    description: Set the schematic of an arena
    permission: spawnarena.setarenaschematic
    permission-message: "§cYou don't have permission!"
  setpastelocation:
    description: Set the paste location of an arena
    permission: spawnarena.setpastelocation
    permission-message: "§cYou don't have permission!"

permissions:
  spawnarena.setarenaspawn:
    default: op
  spawnarena.joinarenaqueue:
    default: op
  spawnarena.createarena:
    default: op
  spawnarena.allowcommandsinfight:
    default: op
  spawnarena.togglearenamode:
    default: op
  spawnarena.setupfight:
    default: op
  spawnarena.setarenaschematic:
    default: op
  spawnarena.setpastelocation:
    default: op