main: me.zeronull.spawnarena.SpawnArena
name: SpawnArena
version: 1.0.0
api-version: '1.20'
softdepend:
  - WorldGuard

commands:
  joinarenaqueue:
    description: join queue
    permission: spawnarena.joinarenaqueue
    permission-message: "§cYou don't have permission!"
  setarenaspawn:
    description: join queue
    permission: spawnarena.setarenaspawn
    permission-message: "§cYou don't have permission!"
  createarena:
    description: Create an arena
    permission: spawnarena.createarena
    permission-message: "§cYou don't have permission!"
  togglearenamode:
    description: Alter the arena mode
    permission: spawnarena.togglearenamode
    permission-message: "§cYou don't have permission!"

permissions:
  spawnarena.setarenaspawn:
    default: op
  spawnarena.joinarenaqueue:
    default: op
  spawnarena.createarena:
    default: op
  spawnarena.allowcommandsinfight:
    default: op
  spawnarena.togglearenamode:
    default: op