main: me.zeronull.spawnarena.SpawnArena
name: SpawnArena
version: 1.0.0
api-version: '1.20'
softdepend:
  - WorldGuard

commands:
  joinarenaqueue:
    description: join queue
  setarenaspawn:
    description: join queue